version: "3.1"

services:
  front-dev:
    image: node:16.17.0
    # container_name: front-dev
    command: bash -c "npm install && npm start"
    # user: "$(id -u):$(id -g)"
    working_dir: /opt/front
    volumes:
      - .:/opt/front
    
    network_mode: "host"

